'use strict';

// ── EU Call Checker tab ──────────────────────────────────────────────────────
// Searches EDF calls via EU Participant Portal public APIs.
// All DOM IDs are prefixed with "ec-" to avoid conflicts with other tabs.

// ── CONFIG ──
const YEARS_TO_TRY = [2027, 2026, 2025, 2024, 2023, 2022, 2021];
const SEARCH_API   = 'https://api.tech.ec.europa.eu/search-api/prod/rest/search';
const DOC_API      = 'https://api.tech.ec.europa.eu/search-api/prod/rest/document';
const PROJECTS_API = 'https://ec.europa.eu/info/funding-tenders/opportunities/api/topicProjectsList.json';
const CACHE_KEY    = 'edf_calls_v1';
const CACHE_TTL_MS = 6 * 3600 * 1000; // 6 hours → triggers silent background refresh
const PAGE_SIZE    = 50;

// ── LOCAL STATE ──
let currentData      = null;
let currentPattern   = null;
let currentYears     = [];
let edfCallsList     = [];       // [{ identifier, title, status, deadline }] for autocomplete
let edfCallsDb       = null;     // full edf_calls.json payload (calls keyed by identifier)
let acReady          = false;    // autocomplete usable?
let acEnterBlocked   = false;    // block Search on Enter when item selected from drop
let fundedOnly       = true;     // filter: show only calls with projects in dropdown
let participantStore = [];       // flat list of participant objects, indexed by render order

// ══════════════════════════════════════════════════════════════════════════════
// CORS PROXY CHAIN
// ══════════════════════════════════════════════════════════════════════════════
async function proxiedFetch(url, options = {}) {
  const isPost = (options.method || 'GET').toUpperCase() === 'POST';
  const chain = isPost
    ? [u => u,
       u => `https://corsproxy.io/?url=${encodeURIComponent(u)}`]
    : [u => u,
       u => `https://api.allorigins.win/raw?url=${encodeURIComponent(u)}`,
       u => `https://corsproxy.io/?url=${encodeURIComponent(u)}`];

  for (const mkUrl of chain) {
    try {
      const r = await fetch(mkUrl(url), options);
      if (r.status !== 403 && r.status !== 429 && r.status !== 408) return r;
    } catch (_) {}
  }
  throw new Error('All CORS proxies failed');
}

// ══════════════════════════════════════════════════════════════════════════════
// CALLS LIST CACHE  (localStorage + stale-while-revalidate)
// ══════════════════════════════════════════════════════════════════════════════

function cacheRead() {
  try {
    const raw = localStorage.getItem(CACHE_KEY);
    if (!raw) return null;
    const obj = JSON.parse(raw);
    return (obj?.data?.length && obj?.timestamp) ? obj : null;
  } catch (_) { return null; }
}

function cacheWrite(data) {
  try {
    localStorage.setItem(CACHE_KEY, JSON.stringify({ data, timestamp: Date.now() }));
  } catch (_) {}
}

/**
 * Load the EDF calls list.
 * Priority: edf_calls.json (static file) → localStorage cache → live API fetch.
 * force=true skips the file and cache, goes straight to API (used by ↺ refresh).
 */
async function loadEdfCalls(force = false) {
  // ── 1. Try static file (generated by fetch_edf_bulk.py) ──────────────────
  if (!force) {
    try {
      const resp = await fetch('data/edf_calls.json');
      if (resp.ok) {
        const json = await resp.json();
        if (json?.calls && Object.keys(json.calls).length > 0) {
          edfCallsDb = json.calls;
          const list = Object.values(json.calls).map(c => ({
            identifier: c.identifier,
            title:      c.title       || '',
            status:     c.status      || '',
            deadline:   c.deadline    || '',
            desc:       (c.description || '').slice(0, 600).toLowerCase(),
          }));
          applyCallsList(list);
          const ts = json._generated_at ? new Date(json._generated_at).getTime() : null;
          setCallStatus('file', ts, `${list.length} calls from file`);
          // Populate header file date
          const fileDateEl = document.getElementById('ec-fileDate');
          if (fileDateEl && json._generated_at) {
            const d = new Date(json._generated_at);
            fileDateEl.textContent = d.toLocaleDateString('en-GB', { day:'2-digit', month:'2-digit', year:'numeric' });
          }
          // Background delta check for new calls
          deltaCheck().catch(() => {});
          return;
        }
      }
    } catch (_) {}

    // ── 2. Fall back to localStorage cache ───────────────────────────────────
    const cached = cacheRead();
    if (cached) {
      applyCallsList(cached.data);
      setCallStatus('ready', cached.timestamp);
      if (Date.now() - cached.timestamp > CACHE_TTL_MS) {
        fetchAllEdfTopics().then(data => {
          if (data.length > 0) { cacheWrite(data); applyCallsList(data); setCallStatus('ready', Date.now()); }
        }).catch(() => {});
      }
      return;
    }
  }

  // ── 3. Live API fetch ─────────────────────────────────────────────────────
  setCallStatus('fetching');
  try {
    const data = await fetchAllEdfTopics();
    if (data.length > 0) {
      cacheWrite(data);
      applyCallsList(data);
      setCallStatus('ready', Date.now());
    } else {
      setCallStatus('empty');
    }
  } catch (err) {
    const cached = cacheRead();
    if (cached) {
      applyCallsList(cached.data);
      setCallStatus('stale', cached.timestamp);
    } else {
      setCallStatus('error', null, err.message);
    }
  }
}

/**
 * Lightweight delta check: fetch one page of the latest year from the API
 * and flag any identifiers not present in edfCallsDb.
 */
async function deltaCheck() {
  if (!edfCallsDb) return;
  try {
    const query = { bool: { must: [{ terms: { type: ['1', '2', '8'] } }] } };
    const url   = `${SEARCH_API}?apiKey=SEDIA&text=${encodeURIComponent('EDF-' + YEARS_TO_TRY[0])}`;
    const body  = new URLSearchParams({ query: JSON.stringify(query), pageNumber: 1, pageSize: PAGE_SIZE });
    const resp  = await proxiedFetch(url, { method: 'POST', body });
    if (!resp.ok) return;
    const results = (await resp.json()).results || [];
    const newCalls = [];
    for (const r of results) {
      const ids = r.metadata?.identifier || [];
      const id  = (Array.isArray(ids) ? ids[0] : ids) || '';
      if (id && id.toUpperCase().startsWith('EDF-') && !edfCallsDb[id.toUpperCase()]) {
        newCalls.push(id.toUpperCase());
      }
    }
    if (newCalls.length > 0) {
      const el = document.getElementById('ec-callStatusText');
      if (el) {
        el.innerHTML += ` · <span style="color:#e3b341;font-weight:700">⚠ ${newCalls.length} new call${newCalls.length > 1 ? 's' : ''} not in file — run fetch_edf_bulk.py --update</span>`;
      }
    }
  } catch (_) {}
}

function applyCallsList(data) {
  edfCallsList = data;
  acReady = true;
  updateHeaderCounts();
  showDropFiltered('');
}

function updateHeaderCounts() {
  const totalEl   = document.getElementById('ec-totalCallsCount');
  const fundedEl  = document.getElementById('ec-fundedCount');
  if (totalEl) totalEl.textContent = edfCallsList.length;
  if (fundedEl) {
    const n = edfCallsDb ? Object.values(edfCallsDb).filter(c => c.projects?.length > 0).length : 0;
    fundedEl.textContent = n ? `(${n})` : '';
  }
}

/** Returns the subset of edfCallsList shown in the dropdown based on current filter. */
function activeList() {
  if (!fundedOnly || !edfCallsDb) return edfCallsList;
  return edfCallsList.filter(c => (edfCallsDb[c.identifier]?.projects?.length ?? 0) > 0);
}

// ── Fetch all EDF topics from the Search API (paginated, year-by-year) ──
// KEY: the API is 1-indexed — pageNumber=1 is the first page, 0 returns nothing.
// pageNumber and pageSize go in the POST body (not the URL).
// We scan up to MAX_PAGES per year and stop early if a page adds 0 new topics.
async function fetchAllEdfTopics() {
  const query    = { bool: { must: [{ terms: { type: ['1', '2', '8'] } }] } };
  const all      = [];
  const seen     = new Set();
  const MAX_PAGES = 8;   // up to 400 results per year before dedup
  const PAGE_SIZE = 50;

  for (const year of YEARS_TO_TRY) {
    let newThisYear = 0;

    for (let page = 1; page <= MAX_PAGES; page++) {  // ← 1-indexed!
      const url  = `${SEARCH_API}?apiKey=SEDIA&text=${encodeURIComponent('EDF-' + year)}`;
      const body = new URLSearchParams({
        query:      JSON.stringify(query),
        pageNumber: page,     // ← 1-indexed, in body
        pageSize:   PAGE_SIZE // ← in body
      });

      let resp;
      try {
        resp = await proxiedFetch(url, { method: 'POST', body });
      } catch (e) {
        console.warn(`[EU Calls] year ${year} p${page}:`, e.message);
        break;
      }
      if (!resp.ok) { console.warn(`[EU Calls] year ${year} p${page} HTTP ${resp.status}`); break; }

      const results = (await resp.json()).results || [];
      let newThisPage = 0;

      for (const r of results) {
        const meta       = r.metadata || {};
        const idArr      = meta.identifier || [];
        const rawId      = (Array.isArray(idArr) ? idArr[0] : idArr) || '';
        if (!rawId) continue;
        const identifier = String(rawId).toUpperCase();
        if (!identifier.startsWith('EDF-')) continue;
        if (seen.has(identifier)) continue;
        seen.add(identifier);
        newThisPage++;

        const get1 = k => { const v = meta[k] || []; return (Array.isArray(v) ? v[0] : v) || ''; };
        all.push({
          identifier,
          title:    get1('title') || get1('topicTitle'),
          status:   get1('status'),
          deadline: get1('deadlineDate') || get1('submissionDeadlineDate')
        });
      }

      console.log(`[EU Calls] ${year} p${page}: ${results.length} results, ${newThisPage} new → total ${all.length}`);

      // Update the autocomplete list progressively so the dropdown is usable
      // even before the full fetch is done
      applyCallsList(all.slice());
      setCallStatus('loading_progress', null, `${all.length} calls found so far…`);

      // Stop early: no new topics on this page, or short page (last page)
      if (newThisPage === 0 || results.length < PAGE_SIZE) break;
      newThisYear += newThisPage;

      await sleep(250);
    }

    await sleep(300);
  }

  console.log(`[EU Calls] done — ${all.length} unique EDF topics`);

  all.sort((a, b) => {
    const ya = parseInt((a.identifier.match(/\d{4}/) || ['0'])[0]);
    const yb = parseInt((b.identifier.match(/\d{4}/) || ['0'])[0]);
    if (yb !== ya) return yb - ya;
    return a.identifier.localeCompare(b.identifier);
  });

  return all;
}

// ── Status bar ──
function setCallStatus(state, timestamp = null, errMsg = '') {
  const el = document.getElementById('ec-callStatusText');
  if (!el) return;

  const refresh = `<a href="javascript:void(0)" id="ec-refreshLink" style="color:var(--accent)">↺ refresh</a>`;

  switch (state) {
    case 'file': {
      const n   = edfCallsList.length;
      const ago = timeSince(timestamp);
      el.innerHTML = `<span style="color:var(--accent);font-weight:700">${n}</span> calls · file ${ago} · ${refresh}`;
      break;
    }
    case 'fetching':
      el.innerHTML = '<span style="opacity:.6">Fetching call list from EU Portal…</span>';
      break;
    case 'loading_progress':
      el.innerHTML = `<span style="opacity:.6">${escHtml(errMsg)}</span>`;
      break;
    case 'ready': {
      const n   = edfCallsList.length;
      const ago = timeSince(timestamp);
      el.innerHTML = `<span style="color:var(--accent);font-weight:700">${n}</span> calls loaded · updated ${ago} · ${refresh}`;
      break;
    }
    case 'stale': {
      const n   = edfCallsList.length;
      const ago = timeSince(timestamp);
      el.innerHTML = `<span style="opacity:.6">${n} calls (cached ${ago}, fetch failed) · ${refresh}</span>`;
      break;
    }
    case 'empty':
      el.innerHTML = `No EDF calls found in API. · ${refresh}`;
      break;
    case 'error':
      el.innerHTML = `<span style="color:#f85149">Could not load call list: ${escHtml(errMsg)}</span> · ${refresh}`;
      break;
  }

  // Wire refresh link (re-created each time innerHTML changes)
  const link = document.getElementById('ec-refreshLink');
  if (link) {
    link.addEventListener('click', () => {
      edfCallsList = [];
      acReady = false;
      loadEdfCalls(true);
    });
  }
}

function timeSince(ts) {
  if (!ts) return '?';
  const diff = Date.now() - ts;
  const mins = Math.floor(diff / 60000);
  if (mins < 1)  return 'just now';
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24)  return `${hrs}h ago`;
  return `${Math.floor(hrs / 24)}d ago`;
}

// ══════════════════════════════════════════════════════════════════════════════
// AUTOCOMPLETE
// ══════════════════════════════════════════════════════════════════════════════

function showDropFiltered(rawQuery) {
  if (!acReady) return;
  const q    = rawQuery.trim().toLowerCase();
  const base = activeList();

  const matches = q.length === 0
    ? base
    : base.filter(c =>
        c.identifier.toLowerCase().includes(q) ||
        c.title.toLowerCase().includes(q) ||
        c.desc.includes(q)
      );

  if (matches.length === 0) { closeDrop(); return; }
  renderDrop(matches.slice(0, 50), rawQuery.trim()); // cap at 50 visible items
}

function initAutocomplete() {
  const input = document.getElementById('ec-topicInput');
  const drop  = document.getElementById('ec-callDrop');
  if (!input || !drop) return;

  // Show all calls on focus (click into field)
  input.addEventListener('focus', () => {
    showDropFiltered(input.value);
  });

  // Filter on typing
  input.addEventListener('input', () => {
    showDropFiltered(input.value);
  });

  // Keyboard navigation
  input.addEventListener('keydown', e => {
    if (!drop.classList.contains('open')) return;

    const items   = [...drop.querySelectorAll('.live-drop-item')];
    const current = drop.querySelector('.live-drop-item.ec-active');
    const idx     = current ? items.indexOf(current) : -1;

    if (e.key === 'ArrowDown') {
      e.preventDefault();
      items.forEach(i => i.classList.remove('ec-active'));
      (items[idx + 1] || items[0]).classList.add('ec-active');
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      items.forEach(i => i.classList.remove('ec-active'));
      (items[idx - 1] || items[items.length - 1]).classList.add('ec-active');
    } else if (e.key === 'Enter') {
      const active = drop.querySelector('.live-drop-item.ec-active');
      if (active) {
        e.preventDefault();
        selectCall(active.dataset.id, input);
      }
    } else if (e.key === 'Escape') {
      closeDrop();
    }
  });

  // Close on outside click
  document.addEventListener('click', e => {
    if (!e.target.closest('#ec-topicInput') && !e.target.closest('#ec-callDrop')) {
      closeDrop();
    }
  });
}

function renderDrop(matches, rawQuery) {
  const drop = document.getElementById('ec-callDrop');
  if (!drop) return;

  const q = rawQuery.toLowerCase();

  drop.innerHTML = matches.map(c => {
    const statusDot = c.status
      ? `<span class="ec-status-dot ec-status-${statusClass(c.status)}"></span>`
      : '';
    const deadlineStr = c.deadline
      ? ` · <span style="opacity:.5">${fmtDate(c.deadline)}</span>`
      : '';
    return `
    <div class="live-drop-item" data-id="${escHtml(c.identifier)}">
      <div class="live-label">${highlight(escHtml(c.title || '—'), q)}</div>
      <div class="live-desc">${highlight(escHtml(c.identifier), q)} ${statusDot}${deadlineStr}</div>
    </div>`;
  }).join('');

  drop.querySelectorAll('.live-drop-item').forEach(item => {
    item.addEventListener('mousedown', e => {
      e.preventDefault(); // prevent input blur before click fires
      selectCall(item.dataset.id, document.getElementById('ec-topicInput'));
    });
  });

  drop.classList.add('open');
}

function selectCall(identifier, input) {
  input.value = identifier;
  closeDrop();
  acEnterBlocked = false;
}

function closeDrop() {
  const drop = document.getElementById('ec-callDrop');
  if (drop) { drop.classList.remove('open'); drop.innerHTML = ''; }
}

/** Wraps matching substrings in <mark> for highlighting */
function highlight(text, query) {
  if (!query || query.length < 2) return text;
  try {
    const re = new RegExp(`(${query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`, 'gi');
    return text.replace(re, '<mark>$1</mark>');
  } catch (_) { return text; }
}

function statusClass(s) {
  if (!s) return 'unknown';
  const l = s.toLowerCase();
  if (l.includes('open'))        return 'open';
  if (l.includes('forthcoming')) return 'forthcoming';
  if (l.includes('closed'))      return 'closed';
  return 'unknown';
}

// ══════════════════════════════════════════════════════════════════════════════
// HELPERS
// ══════════════════════════════════════════════════════════════════════════════

/** Build a scrapeYear-compatible result object from a cached edf_calls.json entry. */
function buildYearDataFromCache(identifier, cached) {
  const projects = (cached.projects || []).map(p => ({
    TITLE:             p.title        || '',
    ACRONYM:           p.acronym      || '',
    'PROJECT ID':      p.project_id   || '',
    URL:               p.url          || '',
    Status:            p.status       || '',
    'Start date':      p.start_date   || '',
    'End date':        p.end_date     || '',
    'Overall budget':  p.overall_budget   || '',
    'EU contribution': p.eu_contribution  || '',
    Objective:         p.objective    || '',
    'Type of action':  p.type_of_action || '',
    Participants: (p.participants || []).map(part => ({
      'Organization Name': part.organization_name  || '',
      PIC:                 part.pic                || '',
      Role:                part.role               || '',
      Country:             part.country            || '',
      'EU Contribution':   part.eu_contribution    || '',
      Status:              part.status             || '',
      // enriched fields from fetch_edf_bulk.py
      eu_url:              part.eu_url             || '',
      activity_type:       part.activity_type      || '',
      organization_type:   part.organization_type  || '',
      type:                part.type               || '',
      sme:                 part.sme,
      country_code:        part.country_code       || '',
      city:                part.city               || '',
      postal_code:         part.postal_code        || '',
      street:              part.street             || '',
      latitude:            part.latitude           || '',
      longitude:           part.longitude          || '',
      web_link:            part.web_link           || '',
      order:               part.order,
    })),
  }));

  let totalBudget = 0, totalEU = 0, totalPart = 0;
  for (const p of projects) {
    totalBudget += parseFloat(p['Overall budget']  || 0) || 0;
    totalEU     += parseFloat(p['EU contribution'] || 0) || 0;
    totalPart   += (p.Participants || []).length;
  }

  return {
    success:            true,
    topic_identifier:   identifier,
    scraping_timestamp: cached._projects_fetched_at || cached._fetched_at || new Date().toISOString(),
    call_info:          { topic_id: cached.ccm2Id || '', topic_description: cached.description || null, budget_overview: cached.budget_overview || null },
    topic_updates:      { total_updates: 0, updates: [] },
    statistics:         { total_projects: projects.length, total_participants: totalPart, total_budget: totalBudget, total_eu_contribution: totalEU },
    projects,
  };
}

// ══════════════════════════════════════════════════════════════════════════════
// MAIN SEARCH HANDLER
// ══════════════════════════════════════════════════════════════════════════════
async function handleSearch() {
  const raw = document.getElementById('ec-topicInput').value.trim().toUpperCase();
  if (!raw) { alert('Please enter a topic identifier'); return; }

  if (!raw.startsWith('EDF-')) {
    showEdfOnlyModal();
    return;
  }

  currentData = null; currentPattern = null; currentYears = [];
  ecHide('ec-resultsSection');
  ecHide('ec-errorSection');
  ecClearLog();
  closeDrop();

  const pattern = extractPattern(raw);
  if (!pattern) {
    showError('Invalid format. Use: EDF-YYYY-SUFFIX (e.g. EDF-2024-RA-SI-MATCOMP-EC-STEP)');
    return;
  }

  setLoading(true);
  ecShow('ec-progressSection');
  setProgress(5, `Pattern found: ${pattern.base}`);

  // ── Fast path: serve from edf_calls.json if projects already fetched ──────
  if (edfCallsDb?.[raw]?.projects?.length > 0) {
    const cached = edfCallsDb[raw];
    ecLog(`Loaded from file (${cached.projects.length} project(s))`, 'ok');
    const yearData = buildYearDataFromCache(raw, cached);
    const found    = [{ year: pattern.year, data: yearData }];
    setProgress(100, 'Done!');
    currentPattern = pattern;
    currentYears   = found;
    currentData    = {
      pattern,
      years: found,
      summary: {
        total_years:        1,
        years_list:         [pattern.year],
        total_projects:     yearData.statistics.total_projects,
        total_participants: yearData.statistics.total_participants,
      }
    };
    setTimeout(() => { ecHide('ec-progressSection'); renderResults(); setLoading(false); }, 300);
    return;
  }

  const found = [];

  // If the identifier includes a specific year, only search that year.
  // Otherwise (wildcard / no year) try all years.
  const yearsToSearch = pattern.year ? [parseInt(pattern.year, 10)] : YEARS_TO_TRY;

  for (let i = 0; i < yearsToSearch.length; i++) {
    const year = yearsToSearch[i];
    const pct  = 10 + Math.round(((i + 1) / yearsToSearch.length) * 80);
    setProgress(pct, `Searching year ${year}… (${i + 1}/${yearsToSearch.length})`);
    ecLog(`Searching ${pattern.prefix}-${year}-${pattern.suffix}…`, 'info');

    try {
      const yearData = await scrapeYear(pattern.prefix, year, pattern.suffix);
      if (yearData) {
        found.push({ year: String(year), data: yearData });
        const np = yearData.statistics.total_projects;
        ecLog(`Year ${year}: found – ${np} project${np === 1 ? '' : 's'}`, 'ok');
      } else {
        ecLog(`Year ${year}: no data`, 'warn');
      }
    } catch (err) {
      ecLog(`Year ${year}: error – ${err.message}`, 'err');
    }
  }

  if (found.length === 0) {
    setLoading(false);
    ecHide('ec-progressSection');
    showError(`No data found for pattern "${pattern.base}" in years 2021–2027.`);
    return;
  }

  found.sort((a, b) => parseInt(b.year) - parseInt(a.year));
  setProgress(100, 'Done!');

  const totalProjects = found.reduce((s, y) => s + y.data.statistics.total_projects, 0);
  const totalPart     = found.reduce((s, y) => s + y.data.statistics.total_participants, 0);

  currentPattern = pattern;
  currentYears   = found;
  currentData    = {
    pattern,
    years: found,
    summary: {
      total_years:        found.length,
      years_list:         found.map(y => y.year),
      total_projects:     totalProjects,
      total_participants: totalPart
    }
  };

  setTimeout(() => {
    ecHide('ec-progressSection');
    renderResults();
    setLoading(false);
  }, 600);
}

// ══════════════════════════════════════════════════════════════════════════════
// SCRAPE SINGLE YEAR
// ══════════════════════════════════════════════════════════════════════════════
async function scrapeYear(prefix, year, suffix) {
  const topicIdentifier = `${prefix}-${year}-${suffix}`;

  // Use JSON file data if available (avoids unreliable text search)
  const cached = edfCallsDb?.[topicIdentifier];
  let topicId, topicDescription, budgetOverview;

  if (cached?.ccm2Id) {
    topicId          = cached.ccm2Id;
    topicDescription = cached.description || null;
    budgetOverview   = cached.budget_overview || null;
    ecLog(`  Using ccm2Id from file: ${topicId}`, 'info');
  } else {
    const meta = await fetchTopicMeta(topicIdentifier);
    if (!meta) return null;
    ({ topicId, topicDescription, budgetOverview } = meta);
  }

  let projects = [];
  try {
    const resp = await fetch(`${PROJECTS_API}?topicId=${encodeURIComponent(topicId)}`);
    if (resp.ok) {
      const raw = await resp.json();
      projects = Array.isArray(raw) ? raw : [];
    }
  } catch (e) {
    ecLog(`  Could not load project list for ${topicIdentifier}: ${e.message}`, 'warn');
  }

  const processed = projects.map(p => ({
    TITLE:        p.title || '',
    ACRONYM:      p.acronym || '',
    'PROJECT ID': p.businessIdentifier || '',
    URL:          `https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/projects-details/${p.programId}/${p.businessIdentifier}`,
    _endpoint:    `${DOC_API}/${p.programId}${p.businessIdentifier}?apiKey=SEDIA_NONH2020_PROD`
  }));

  const detailed = [];
  for (let i = 0; i < processed.length; i++) {
    try { detailed.push(await fetchProjectDetails(processed[i])); }
    catch (_) { detailed.push(processed[i]); }
    if (i < processed.length - 1) await sleep(800);
  }

  const updates = await fetchTopicUpdates(topicIdentifier);

  let totalBudget = 0, totalEU = 0, totalPart = 0;
  for (const p of detailed) {
    totalBudget += parseFloat(p['Overall budget']  || 0) || 0;
    totalEU     += parseFloat(p['EU contribution'] || 0) || 0;
    totalPart   += (p.Participants || []).length;
  }

  return {
    success:            true,
    topic_identifier:   topicIdentifier,
    scraping_timestamp: new Date().toISOString(),
    call_info:          { topic_id: topicId, topic_description: topicDescription, budget_overview: budgetOverview },
    topic_updates:      { total_updates: updates.length, updates },
    statistics:         { total_projects: detailed.length, total_participants: totalPart, total_budget: totalBudget, total_eu_contribution: totalEU },
    projects:           detailed
  };
}

// ══════════════════════════════════════════════════════════════════════════════
// EU API CALLS
// ══════════════════════════════════════════════════════════════════════════════
async function fetchTopicMeta(topicIdentifier) {
  const query = {
    bool: { must: [{ terms: { type: ['1', '2', '8'] } }, { term: { identifier: topicIdentifier } }] }
  };
  // Use the suffix only as search text (drops EDF-YYYY prefix) to avoid
  // year-bucket competition that pushes the exact doc out of top results.
  const suffix = topicIdentifier.replace(/^EDF-\d{4}-/i, '') || topicIdentifier;
  const url  = `${SEARCH_API}?apiKey=SEDIA&text=${encodeURIComponent(suffix)}`;
  const body = new URLSearchParams({ query: JSON.stringify(query), pageNumber: 1, pageSize: 50 });

  let resp;
  try { resp = await proxiedFetch(url, { method: 'POST', body }); }
  catch (e) { throw new Error(`Search API unreachable: ${e.message}`); }

  if (!resp.ok) return null;
  const data    = await resp.json();
  const results = data.results || [];
  if (results.length === 0) return null;

  ecLog(`  API returned ${results.length} result(s) for ${topicIdentifier}`, 'info');
  results.slice(0, 3).forEach(r => {
    const ids   = r.metadata?.identifier || r.metadata?.topicCode || [];
    const idStr = Array.isArray(ids) ? ids.join(', ') : ids;
    ecLog(`    → ref: ${r.reference || '?'} | identifier: ${idStr}`, 'info');
  });

  const idUpper = topicIdentifier.toUpperCase();
  const match   = results.find(r => {
    const ids   = r.metadata?.identifier || r.metadata?.topicCode || [];
    const idArr = Array.isArray(ids) ? ids : [ids];
    return idArr.some(id => (id || '').toUpperCase() === idUpper);
  });
  if (!match) return null;

  const meta    = match.metadata || {};
  const ccm2Id  = meta.ccm2Id;
  const topicId = ccm2Id ? (Array.isArray(ccm2Id) ? ccm2Id[0] : ccm2Id) : null;
  if (!topicId) return null;

  const descArr          = meta.descriptionByte;
  const topicDescription = descArr && descArr.length > 0 ? descArr[0] : null;

  let budgetOverview = null;
  const budgetRaw = meta.budgetOverview;
  if (budgetRaw && budgetRaw.length > 0) {
    try { budgetOverview = JSON.parse(budgetRaw[0]); } catch (_) {}
  }

  return { topicId, topicDescription, budgetOverview };
}

async function fetchProjectDetails(project) {
  const resp = await proxiedFetch(project._endpoint);
  if (!resp.ok) return project;

  const data = await resp.json();
  const meta = data.metadata || {};
  const get1 = (k, def = '') => { const v = meta[k]; return (v && v.length > 0) ? v[0] : def; };

  project.Status             = get1('status');
  project['Start date']      = get1('startDate');
  project['End date']        = get1('endDate');
  project['Overall budget']  = normBudget(get1('overallBudget'));
  project['EU contribution'] = normBudget(get1('euContributionAmount'));
  project.Objective          = get1('objective');
  project['Type of action']  = get1('typeOfAction');

  const partJson   = get1('participants', '[]');
  let participants = [];
  try {
    participants = JSON.parse(partJson).map(p => {
      const cc      = p.postalAddress?.countryCode;
      const country = (cc && typeof cc === 'object') ? cc.description : (cc || '');
      const pic     = String(p.pic || '');
      return {
        'Organization Name': p.legalName || '',
        PIC:                 pic,
        Role:                p.role || '',
        Country:             country,
        'EU Contribution':   normBudget(p.eucontribution || ''),
        Status:              p.status || '',
        eu_url:              pic ? `https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/how-to-participate/org-details/${pic}` : '',
      };
    });
  } catch (_) {}
  project.Participants = participants;
  return project;
}

async function fetchTopicUpdates(topicIdentifier) {
  const query = {
    bool: { must: [{ terms: { type: ['6'] } }, { term: { identifier: topicIdentifier } }] }
  };
  try {
    const url  = `${SEARCH_API}?apiKey=SEDIA&text=${encodeURIComponent(topicIdentifier)}`;
    const body = new URLSearchParams({ query: JSON.stringify(query) });
    const resp = await proxiedFetch(url, { method: 'POST', body });
    if (!resp.ok) return [];
    const data    = await resp.json();
    return (data.results || []).map(u => {
      const m = u.metadata || {};
      return {
        reference:   u.reference || null,
        date:        (m.startDate   || [null])[0],
        title:       (m.title       || [null])[0],
        description: (m.description || [null])[0],
        language:    (m.language    || [null])[0]
      };
    }).sort((a, b) => (b.date || '') > (a.date || '') ? 1 : -1);
  } catch (_) { return []; }
}

// ══════════════════════════════════════════════════════════════════════════════
// RENDER RESULTS
// ══════════════════════════════════════════════════════════════════════════════
function renderResults() {
  participantStore = [];   // reset on each new search
  ecShow('ec-resultsSection');

  const yearsDisplay = currentYears.map(y => ({
    year:         y.year,
    topic:        `${currentPattern.prefix}-${y.year}-${currentPattern.suffix}`,
    callInfo:     y.data.call_info,
    statistics:   y.data.statistics,
    projects:     y.data.projects,
    topicUpdates: y.data.topic_updates
  }));

  document.getElementById('ec-patternTitle').textContent = `Pattern: ${currentPattern.base}`;

  const totalProjects = currentYears.reduce((s, y) => s + y.data.statistics.total_projects, 0);
  document.getElementById('ec-yearsbadges').innerHTML =
    `<strong>Years found:</strong> ` +
    yearsDisplay.map(y => `<span class="badge bg-primary ms-1">${y.year}</span>`).join('') +
    ` <span class="text-muted ms-2">(${currentYears.length} edition${currentYears.length === 1 ? '' : 's'})</span>` +
    ` <span class="badge bg-success ms-2">${totalProjects} total project${totalProjects === 1 ? '' : 's'}</span>`;

  buildComparisonTable(yearsDisplay);
  buildAccordion(yearsDisplay);
}

// ── Comparison table ──
function buildComparisonTable(yearsDisplay) {
  const card = document.getElementById('ec-comparisonTable')?.closest('.card');
  if (card) card.style.display = yearsDisplay.length < 2 ? 'none' : '';
  const table = document.getElementById('ec-comparisonTable');
  let html = '<thead><tr><th>Metric</th>';
  yearsDisplay.forEach(y => { html += `<th>${y.year}</th>`; });
  html += '</tr></thead><tbody>';
  [
    ['Projects',        y => y.statistics.total_projects],
    ['Participants',    y => y.statistics.total_participants],
    ['Call Budget',     y => fmtCurrency(extractCallBudget(y))],
    ['Project Budget',  y => fmtCurrency(y.statistics.total_budget)],
    ['EU Contribution', y => fmtCurrency(y.statistics.total_eu_contribution)]
  ].forEach(([label, fn]) => {
    html += `<tr><td><strong>${label}</strong></td>`;
    yearsDisplay.forEach(y => { html += `<td>${fn(y)}</td>`; });
    html += '</tr>';
  });
  html += '</tbody>';
  table.innerHTML = html;
}

function extractCallBudget(yearData) {
  const ci = yearData.callInfo;
  if (!ci || !ci.budget_overview) return 0;
  const bm  = ci.budget_overview.budgetTopicActionMap || {};
  const tid = yearData.topic || '';
  let total = 0;
  for (const aid in bm) {
    (bm[aid] || []).forEach(action => {
      if ((action.action || '').toUpperCase().includes(tid.toUpperCase())) {
        Object.values(action.budgetYearMap || {}).forEach(v => { total += parseFloat(v) || 0; });
      }
    });
  }
  return total;
}

// ── Accordion ──
function buildAccordion(yearsDisplay) {
  document.getElementById('ec-yearsAccordion').innerHTML =
    yearsDisplay.map((yd, i) => createAccordionItem(yd, i)).join('');
}

function createAccordionItem(yd, idx) {
  const { year, topic, statistics, projects } = yd;
  const callUrl = `https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-details/${topic}`;

  const projectsHtml = projects.length > 0
    ? `<div class="proj-list">${projects.map((p, i) => projectCard(p, i)).join('')}</div>`
    : `<div class="alert alert-info">
         <h6 class="alert-heading">No funded projects</h6>
         <p class="mb-0">The call exists but has no projects assigned yet.</p>
       </div>`;

  return `
  <div class="ec-year-block mb-4">
    <div class="ec-year-header">
      <strong>Year ${year}</strong>
      <span class="ms-3 badge bg-primary">${statistics.total_projects} project${statistics.total_projects === 1 ? '' : 's'}</span>
      <span class="ms-2 badge bg-success">${statistics.total_participants} participants</span>
      <span class="ms-2 badge bg-info text-dark">${fmtBudgetShort(statistics.total_eu_contribution)} EU</span>
      <a href="${callUrl}" target="_blank" class="ms-3 text-decoration-none">
        <small>Participant Portal &rarr;</small>
      </a>
    </div>
    <div class="ec-year-body">
      ${projectsHtml}
    </div>
  </div>`;
}

function projectCard(project, idx) {
  const participants = project.Participants || [];
  const partListHtml = participants.length > 0
    ? `<div class="mt-3">
         <strong>All Participants (${participants.length}):</strong>
         <ul class="mt-1 participants-list ps-3">
           ${participants.map(p => {
             const role = (p.Role || '').toLowerCase() === 'coordinator' ? 'Coord.' : 'Partner';
             const idx  = participantStore.push(p) - 1;
             return `<li>
               <span class="ec-part-role">${role}:</span>
               <button class="ec-part-btn" data-pidx="${idx}">${escHtml(p['Organization Name'] || 'N/A')}</button>
               <span class="ec-part-country">(${escHtml(p.Country || 'N/A')})</span>
             </li>`;
           }).join('')}
         </ul>
       </div>`
    : '<p class="ec-no-participants">No participants available</p>';

  const sc = getStatusClass(project.Status);

  return `
  <div class="card mb-3 project-card">
    <div class="card-header">
      <strong>${idx + 1}. ${escHtml(project.ACRONYM || 'N/A')}</strong>
      &nbsp;–&nbsp;${escHtml(project.TITLE || 'No title')}
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-5 project-data-column">
          <p><strong>EU Contribution:</strong> ${fmtCurrency(project['EU contribution'])}</p>
          <p><strong>Total Budget:</strong> ${fmtCurrency(project['Overall budget'])}</p>
          <p><strong>Participants:</strong> ${participants.length}</p>
          <p><strong>Status:</strong> <span class="badge ${sc}">${escHtml(project.Status || 'N/A')}</span></p>
          <p><strong>Duration:</strong> ${fmtDate(project['Start date'])} &rarr; ${fmtDate(project['End date'])}</p>
          <p><strong>Project ID:</strong> ${escHtml(project['PROJECT ID'] || 'N/A')}</p>
          ${partListHtml}
          <div class="mt-3">
            ${project.URL ? `<a href="${project.URL}" target="_blank" class="btn btn-sm btn-outline-primary">View on EU Portal</a>` : ''}
          </div>
        </div>
        <div class="col-md-7">
          <div class="border-start ps-3">
            <h6 class="text-primary mb-2">Objective</h6>
            <div class="ec-objective-scroll">
              <p class="text-justify">${escHtml(project.Objective || 'No objective available')}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>`;
}

// ══════════════════════════════════════════════════════════════════════════════
// JSON MODAL
// ══════════════════════════════════════════════════════════════════════════════
function showJson() {
  if (!currentData) return;
  document.getElementById('ec-copyJsonBtn').textContent = 'Copy';
  document.getElementById('ec-jsonContent').textContent = JSON.stringify(currentData, null, 2);
  new bootstrap.Modal(document.getElementById('ec-jsonModal')).show();
}

function copyJson() {
  const btn = document.getElementById('ec-copyJsonBtn');
  navigator.clipboard.writeText(document.getElementById('ec-jsonContent').textContent)
    .then(() => { btn.textContent = 'Copied!'; setTimeout(() => btn.textContent = 'Copy', 2000); })
    .catch(() => { btn.textContent = 'Error';   setTimeout(() => btn.textContent = 'Copy', 2000); });
}

function downloadJson() {
  if (!currentData) return;
  const fname = currentPattern
    ? `${currentPattern.base}_${new Date().toISOString().split('T')[0]}.json`
    : `callchecker_${new Date().toISOString().split('T')[0]}.json`;
  const blob = new Blob([JSON.stringify(currentData, null, 2)], { type: 'application/json' });
  const a    = document.createElement('a');
  a.href     = URL.createObjectURL(blob);
  a.download = fname;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a); URL.revokeObjectURL(a.href);
}

// ══════════════════════════════════════════════════════════════════════════════
// UI HELPERS
// ══════════════════════════════════════════════════════════════════════════════
function setLoading(on) {
  const btn = document.getElementById('ec-searchBtn');
  btn.disabled = on;
  document.getElementById('ec-btnText').textContent    = on ? 'Running…' : 'Search';
  document.getElementById('ec-btnSpinner').style.display = on ? 'inline-block' : 'none';
}

function setProgress(pct, msg) {
  const bar = document.getElementById('ec-progressBar');
  bar.style.width = pct + '%';
  bar.textContent = pct + '%';
  document.getElementById('ec-progressMsg').innerHTML = `<strong>${escHtml(msg)}</strong>`;
}

function ecShow(id) { const el = document.getElementById(id); if (el) { el.classList.remove('hidden'); el.style.display = ''; } }
function ecHide(id) { const el = document.getElementById(id); if (el) el.style.display = 'none'; }

function showError(msg) {
  document.getElementById('ec-errorMsg').textContent = msg;
  ecShow('ec-errorSection');
}

function showEdfOnlyModal() {
  new bootstrap.Modal(document.getElementById('ec-edfOnlyModal')).show();
}

function ecLog(msg, type = 'info') {
  const panel = document.getElementById('ec-logPanel');
  const d = document.createElement('div');
  d.className   = `ec-log-line ${type}`;
  d.textContent = msg;
  panel.appendChild(d);
  panel.scrollTop = panel.scrollHeight;
}

function ecClearLog() { document.getElementById('ec-logPanel').innerHTML = ''; }

// ══════════════════════════════════════════════════════════════════════════════
// UTILITY
// ══════════════════════════════════════════════════════════════════════════════
function extractPattern(identifier) {
  const m = identifier.match(/^(.+?)-(\d{4})-(.+)$/);
  if (!m) return null;
  const [, prefix, year, suffix] = m;
  return { base: `${prefix}-${suffix}`, year, prefix, suffix };
}

function normBudget(val) {
  if (!val) return '';
  const s = String(val).replace(/[€$,\s]/g, '');
  return isNaN(parseFloat(s)) ? '' : s;
}

function fmtCurrency(val) {
  if (!val && val !== 0) return '-';
  const n = parseFloat(String(val).replace(/[€$,\s]/g, ''));
  if (isNaN(n) || n === 0) return '-';
  return new Intl.NumberFormat('it-IT', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(n);
}

function fmtBudgetShort(val) {
  const n = parseFloat(val);
  if (!n || isNaN(n)) return '-';
  return (n / 1e6).toFixed(1) + 'M €';
}

function fmtDate(ds) {
  if (!ds) return '-';
  try { return new Date(ds).toLocaleDateString('en-GB', { year: 'numeric', month: '2-digit', day: '2-digit' }); }
  catch (_) { return ds; }
}

function escHtml(text) {
  if (!text) return '';
  return String(text).replace(/[&<>"']/g, c => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]
  ));
}

function getStatusClass(status) {
  if (!status) return 'badge-default';
  const s = status.toLowerCase();
  if (s.includes('ongoing'))    return 'badge-ongoing';
  if (s.includes('closed') || s.includes('ended')) return 'badge-closed';
  if (s.includes('forthcoming')) return 'badge-forth';
  return 'badge-default';
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

// Expose tryExample globally (called from onclick in index.html)
window.ecTryExample = function(value) {
  const input = document.getElementById('ec-topicInput');
  input.value = value;
  input.focus();
  input.dispatchEvent(new Event('input'));
};

// ══════════════════════════════════════════════════════════════════════════════
// PARTICIPANT SIDEBAR
// ══════════════════════════════════════════════════════════════════════════════

function openParticipantSidebar(idx) {
  const p   = participantStore[idx];
  if (!p) return;
  const sid = document.getElementById('ec-partSidebar');
  if (!sid) return;

  const name    = p['Organization Name'] || 'N/A';
  const pic     = p.PIC  || '';
  const role    = p.Role || '';
  const country = [p.street, p.city, p.postal_code, p.country_code || p.Country].filter(Boolean).join(', ');
  const euUrl   = p.eu_url || (pic ? `https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/how-to-participate/org-details/${pic}` : '');
  const webLink = p.web_link || '';
  const web     = webLink ? (webLink.startsWith('http') ? webLink : `https://${webLink}`) : '';

  const row = (label, val) => val
    ? `<div class="ec-part-row"><span class="ec-part-label">${label}</span><span class="ec-part-val">${val}</span></div>`
    : '';

  document.getElementById('ec-partTitle').textContent = name;

  document.getElementById('ec-partBody').innerHTML = `
    ${row('Role',          escHtml(role))}
    ${row('PIC',           escHtml(pic))}
    ${row('Activity type', escHtml(p.activity_type || ''))}
    ${row('Org. type',     escHtml(p.organization_type || p.type || ''))}
    ${row('SME',           p.sme === true ? 'Yes' : p.sme === false ? 'No' : '')}
    ${row('Address',       escHtml(country))}
    ${row('Status',        escHtml(p.Status || ''))}
    ${row('EU contribution', p['EU Contribution'] ? fmtCurrency(p['EU Contribution']) : '')}
    ${web  ? `<div class="ec-part-row"><span class="ec-part-label">Website</span><span class="ec-part-val"><a href="${escHtml(web)}" target="_blank" class="ec-part-link">${escHtml(webLink)}</a></span></div>` : ''}
    ${euUrl ? `<div class="mt-3"><a href="${escHtml(euUrl)}" target="_blank" class="btn btn-sm btn-outline-success w-100">View on EU Funding Portal ↗</a></div>` : ''}
    ${p.latitude && p.longitude
      ? `<div class="mt-2 ec-part-row"><span class="ec-part-label">Coords</span><span class="ec-part-val ec-part-val--dim">${p.latitude}, ${p.longitude}</span></div>`
      : ''}
  `;

  sid.classList.add('open');
}

function closeParticipantSidebar() {
  document.getElementById('ec-partSidebar')?.classList.remove('open');
}

// Wire participant clicks (event delegation on the results section)
function initParticipantSidebar() {
  document.getElementById('ec-resultsSection').addEventListener('click', e => {
    const btn = e.target.closest('.ec-part-btn');
    if (btn) openParticipantSidebar(parseInt(btn.dataset.pidx, 10));
  });
  document.getElementById('ec-partClose')?.addEventListener('click', closeParticipantSidebar);
  document.getElementById('ec-partOverlay')?.addEventListener('click', closeParticipantSidebar);
}

// ══════════════════════════════════════════════════════════════════════════════
// INIT (lazy — called on first tab visit)
// ══════════════════════════════════════════════════════════════════════════════
export default function initEucalls() {
  // Wire search button + Enter key
  document.getElementById('ec-searchBtn').addEventListener('click', handleSearch);
  document.getElementById('ec-topicInput').addEventListener('keypress', e => {
    if (e.key === 'Enter') handleSearch();
  });

  // Wire JSON modal buttons
  document.getElementById('ec-viewJsonBtn').addEventListener('click', showJson);
  document.getElementById('ec-copyJsonBtn').addEventListener('click', copyJson);
  document.getElementById('ec-downloadJsonBtn').addEventListener('click', downloadJson);

  // Wire funded-only filter toggle
  const toggle = document.getElementById('ec-fundedOnly');
  if (toggle) {
    toggle.addEventListener('change', () => {
      fundedOnly = toggle.checked;
      showDropFiltered(document.getElementById('ec-topicInput').value);
    });
  }

  // Init autocomplete UI
  initAutocomplete();

  // Init participant sidebar
  initParticipantSidebar();

  // Load (or restore from cache) the EDF calls list
  loadEdfCalls();
}
